name: Machinekit
highlighter: pygments
relative_permalinks: false
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
repository: https://github.com/machinekit/machinekit
baseurl: /machinekit.github.io
